version: '2'
services:
  vanguard:
      image: vanguard.image
      ports:
        - "80:80"
      links:
        - cookiefactory:krustykookies
  cookiefactory:
      image: cookiefactory.image
      ports:
        - "8123:80"
networks:
  default:
    external:
      name: "vanguard-bridge"
