version: '2'
services:
  vanguard:
    image: vanguard.image
    volumes:
      - ./certs:/certs
    ports:
      - "80:80"
      - "443:443"
    links:
      - cookiefactory:krustykookies
      - letsencrypt-auto:letsencrypt-auto
      - rsyslog:rsyslog
  cookiefactory:
    image: cookiefactory.image
    ports:
      - "8123:80"
  letsencrypt-auto:
    image: letsencrypt-auto.image
    container_name: letsencrypt-auto
    volumes:
      - ./certs:/certs
    restart: always
    environment:
      - DOMAINS=vlthr.io,krustykookies.vlthr.io,cv.vlthr.io
      - EMAIL=webmaster@vlthr.io
      - CONCAT=true   # Concatenate the cert chain and the private key into a single file (for applications like HAProxy)
      - SEPARATE=false # Do not create separate certs for each domain
  rsyslog:
    image: robbert229/rsyslog
    ports:
    - 514:514/udp
    - 514:514
    volumes:
    - "./syslog:/var/log/syslog"
networks:
  default:
    external:
      name: "vanguard-bridge"
