version: '2'
services:
  vanguard:
    image: vanguard.image
    volumes:
      - certs:/certs
    ports:
      - "80:80"
      - "443:443"
    links:
      - put-next-main-site-here:main
      - letsencrypt-auto:letsencrypt-auto
      - rsyslog:rsyslog
  letsencrypt-auto:
    image: letsencrypt-auto.image
    container_name: letsencrypt-auto
    volumes:
      - certs:/certs
    restart: always
    environment:
      - DOMAINS=vlthr.io,blog.vlthr.io,cv.vlthr.io
      - EMAIL=webmaster@vlthr.io
      - CONCAT=true   # Concatenate the cert chain and the private key into a single file (for applications like HAProxy)
      - SEPARATE=false # Do not create separate certs for each domain
  rsyslog:
    image: robbert229/rsyslog
    ports:
    - 514:514/udp
    - 514:514
    volumes:
    - "./syslog:/var/log/syslog"
networks:
  default:
    external:
      name: "vanguard-bridge"
volumes:
  certs:
